version: "3.8"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  redis_db:
    container_name: db_container
    image: redis:latest
    restart: always
    volumes:
      - redis_db:/data/db

  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
      - redis_db
