version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: db_container
    restart: always
    volumes:
      - mongo_db:/data/db

  

  api:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
